### ISSUE TITLE
Crash avec fichiers de plus de 4Go

### ISSUE THREAD

**Issue by am-beta** [betagouv/ds_proxy#61]
Lorsque `ds_proxy` fait transiter un fichier, l'application coupe sans prévenir la connexion avec le client (qui envoie le fichier) lorsque 4Go ont été atteints. Côté client, une erreur _Broken Pipe_ arrive.

**Comment by LeSim** [comment]
en fait, c'est probablement le backend ovh qui ne supporte pas de si gros fichier en 1 fois  : https://docs.openstack.org/swift/latest/api/large_objects.html
